service: hello-world
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          path: hello
          method: GET
          cors: true
